name: Docker Image CI for AMD64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allow manual run of the pipeline
  workflow_dispatch:

env:
  CURRENT_DATE: $(date +%y%m%d)


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build the Docker image
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push the image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          # To define a custom registry
          # registry: docker.pkg.github.com
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/rasp-test:latest
            ${{secrets.DOCKERHUB_USERNAME }}/rasp-test:latest-{{github.ref_name}}-$CURRENT_DATE